
version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Hello"
          command: echo Hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "world"
          command: echo  Menna

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
