version: 2.1
command:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Hello"
          command: echo Hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "world"
          command: echo  Menna
  print_myname:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "env var echo my name"
          command: echo $MY_VAR_1
  saved_hello_menna_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "save hello menna text"
          command: echo "Hello Menna" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  print_workflow_id:
    docker:
       - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  hello_error:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run:
          name: on error
          command: echo "Hello Error!"
          when: on_fail

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  hello-workflow:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_myname
      - saved_hello_menna_output
      - print_output_file:
          requires:
          - saved_hello_menna_output
      - print_workflow_id
      - hello_error

